# Generated by Django 2.1.7 on 2019-03-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_edital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edital',
            options={'verbose_name': 'Edital', 'verbose_name_plural': 'Editais'},
        ),
    ]
